title: ""
author: "Jack Storror Carter"
description: "Last updated<br><b>15 January 2024</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  #- {title: Home, file: "index.md", icon: house, sidebaricon: house}
  #- {file: "publications.md"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: CV, url: "https://jackstorrorcarter.github.io/files/CV.pdf", icon: file}
  - {title: Google scholar, icon: scroll, url: "https://scholar.google.com/citations?user=an5KmCEAAAAJ&hl=en&oi=ao"}
  - {title: Contact me, icon: envelope, url: "mailto:jack.carter@dima.unige.it"}
#  - {title: Check out my Github, icon: github, url: "https://github.com/lauraguzmanrincon"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
